### ISSUE TITLE
In Version 1.2 of Simplex, use of Folder command in the ps1 causes MethodException

### ISSUE THREAD

**Issue by DonPwrShellHunt** [beefarino/simplex#1]
Example taken straight from Readme

PS C:\test> cat .\myDrive.ps1
root {
   folder MyFolder {
       script MyEnvironment -id key {
           dir env:
       }
       script MyModules -id guid {
            get-module
       }
   }
}

PS C:\test> New-PSDrive -Name MD -PSProvider Simplex -Root 'C:\Test\myDrive.ps1'
New-PSDrive : Cannot find an overload for "Folder" and the argument count: "1".
At line:1 char:1
- New-PSDrive -Name MD -PSProvider Simplex -Root 'C:\Test\myDrive.ps1'
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [New-PSDrive], MethodException
  - FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewPSDriveCommand

PS C:\test> Get-Module Simplex | FL Name,Version

Name    : Simplex
Version : 1.2.0.0

When I created a ps1 that only used the root and script commands, the New-PSDrive command was successful and navigation through the simplex based drive worked fine.

PS C:\test> $PSVersionTable

Name                           Value

---

PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

**Comment by beefarino** [comment]
Yes, noticed this last night and forgot to push the code.  The latest fix is in commit f8969a5a71195be62744ed2a3d4f0d7f9b94e8d4
